global:
  imageRegistry: docker.ops.premiscale.com
  imagePullSecrets:
    - nexus-docker-registry
  storageClass: longhorn

image:
  name: autoscaler
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 0.1
    memory: 300Mi
  limits:
    cpu: 1.0
    memory: 2Gi

service:
  enabled: true
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

securityContext: {}

api:
  enabled: true
  listeningPort: 8080

env:
  - name: DOPPLER_TOKEN
    valueFrom:
      secretKeyRef:
        name: doppler
        key: doppler_token