global:
  imageRegistry: docker.ops.premiscale.com
  imagePullSecrets:
    - nexus-docker-registry
  storageClass: longhorn

image:
  name: autoscaler
  version: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 0.1
    memory: 300Mi
  limits:
    cpu: 1.0
    memory: 2Gi

service:
  enabled: true
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
