global:
  imageRegistry: docker.ops.premiscale.com
  imagePullSecrets:
    - nexus-docker-registry
  storageClass: longhorn

image:
  name: influxdb
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 0.5
    memory: 500Mi
  limits:
    cpu: 1.0
    memory: 1Gi

securityContext: {}

env:
  - name: DOPPLER_TOKEN
    valueFrom:
      secretKeyRef:
        name: doppler
        key: doppler_token

adminUser:
  bucket: default
  user: admin
  retention_policy: "0s"
  existingSecret: influxdb-passwords

ports:

service:
  enabled: true
  ports: []