
# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  name: autoscaler
  description: Libvirt autoscaler
  homepage: helm.aperiodicity.com
  topics: KVM, virtual machine, libvirt, autoscaling, autoscaler

  # I want to document processes with this project.
  has_wiki: true
