_extends: .github

repository:
  name: premiscale
  description: The PremiScale autoscaling controller for Kubernetes
  homepage: https://premiscale.com
  topics: KVM, libvirt, autoscaling, virtualization, Kubernetes
