_extends: .github-private

repository:
  name: premiscale
  description: PremiScale autoscaler
  homepage: https://github.com/premiscale/premiscale
  topics: KVM, libvirt, autoscaling
  private: true
