_extends: .github

repository:
  name: premiscale
  description: The PremiScale autoscaler controller for Kubernetes
  homepage: https://www.premiscale.com
  topics: KVM, libvirt, autoscaling, virtualization, Kubernetes
