
# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  # See https://docs.github.com/en/rest/reference/repos#update-a-repository for all available settings.
  name: autoscaler
  description: Libvirt autoscaler
  homepage: helm.aperiodicity.com
  topics: KVM, virtual machine, libvirt, autoscaling, autoscaler

  # I want to document processes with this project.
  has_wiki: true

  has_projects: false

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts:
          - autoscaler
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []

  - name: gh-pages
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions:
          users: []
          teams: []
      required_status_checks:
        strict: true
        contexts: []
      enforce_admins: true
      required_linear_history: true
      restrictions:
        apps: []
        users: []
        teams: []
