_extends: .github

repository:
  name: autoscaler
  description: Libvirt autoscaler
  homepage: https://github.com/premiscale/autoscaler
  topics: KVM, virtual machine, libvirt, autoscaling, autoscaler
