apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: influxdb-passwords
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    type: Opaque
  encryptedData:
    influxdb-password: AgBx+PEPWWxC16R50BR7MU9/vSCEB6yzy94q+IHxjNQvnu69Srq855hCXLUzgRGM6luA8eqzgb2rIwH2otN9g6DkzevkmpLX4ed92Vx7WfnelFrLs08FfzabF3VPpVgQJy9V+rN09kevk/ab0Zqr2Cvlsb4eFR4sNQAyV+yu+l5hcNp3lqGKnOkfCk7G+X3uRTZ8MGi5BMHdHZRkIuyVztbEFckKyTTdi11dPeXh/l2Q0Gk70IYHCcRRIVhJLR6MAeOCprBvOdHctgGWnv3ngBCtaGE0Zp4StkqBtEvvBV+TDbQ+GYAxFJ9Eg3Y2ZGNyH0XxVM43V9KY/ES7Qqg/gH5ubRW1z8z6OxBqQNS+Gy8dCqXy+hIf1cwL7MBCukUW19Sv8NLyvMy3RRgp57I8bqU5G55mCpMxj1BAXAu9QuXzVHhUj9yeMXAMsHCFCnCiOb+J6t8hBvInzN+MYRYpOrPfEmOfQP5IyzUZftGcc85OUCJEhU71d8XoOuHD4D5CpLrle/xVfOhMoOmNlsp7ote/OpvE3OCqpSj2meDj5YbW4iYgfzS0T2yzdTtfxmqk41r769ic3HEwFFXyJFGCulDDIOqe7uNuxPIpLVq7cmJIv8LEmvwJOIW/+SCLneFkb3An4+WORhUyfj3A7Py6YUflqaO1Ao3pUULTeae9gto1Q2eUST7l3Yl6T5ONuf4z6luNYtMPKwkIhBNZTlVF9x2Hp5dWhXtiUcUtEq+DP1IvE7o=
    influxdb-user: AgCGcanDOb8n76I8LU/m11UmYhpwJ/hHMUH26NnHirPoLHv3Dmn1IsnpAyDqAiiKEPVvcBlV+D+yHknz6Pxho44i+IvWpvHXpFZvEA/+FRlMlD3J//eMOKTTJDuMquZf6ADJ2enShGDsyPfM/qTqz9yzw00937AmrwEiTVdqh2BmSAUtQn5d2zKdlr72J6ApWlYZrNqghj9jVQwEJ6qF78s+xBc+0dLUQ27Csj2carVZw6asrdLtOrDqHl9P2jJ2NxVNOGTGfX8WVbGJC5nfJ9HcggOVT8GsUxo8qx75fzmNNjvEDo5uSJg3Rd71pG6j9wCyaL/nluvZyqhZKQdE8Sczhp6U6Om2cT6dO8YZ/5IsjdG3yFyaS3hQGpmlf4QT5PIxVExQ8YC6zbho5G8Faw0e7y7DQucY53KIkrgz1sYNsqnjPc23QlJy0YJA7igQoGlncXigt6eqtStxExgk5AbLoeWsaJGXZ9inqxFQUu6gQZRrZvSWfii69JRn4DhyAiMhPnSXtuMDpbjDshcswF8HsprD38N5sg9XgHSQgTIlAaL3vFTNrCNVFsVGG44GyPbX8e3iA4eDnfl9At0dgMHSgK+yj2kdw5Wx9WxAobLt/NjeCwlrHr9GUSoPsqxMC7/w1v6/5FHnKZBWCnXcrEwZ20rrQ5u/2GS2Yk9et7JpvtcqmPUkyjKGiFpPBMMRWjKoMPhwErw=
{{- if not (lookup "v1" "Secret" "platform-develop" "nexus-docker-registry") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: nexus-docker-registry
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  template:
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: AgCZZMfzg1YSDYO/L2Go4ApZGbkaEY2oIHrD6pCn2exRDxXYOl/4N55T/G2bREuXdf14lX6Za/A6JOIazI3/Tj5TRbFNPnMw6nkgO+5oIj5MC5quIdMH1NVbvW/Q4FJY/tQdxCvi8OFaiBYg+E+7cwka3TORiJ6YJWGS1qD6UkihPBLdMnxUVDTVuYIN0IbaiswuH/AeFG9FoWEPu9RN56YOY7vzzmDNsT2EvARDsw9dp42QusVpSyE1TtP3QYQgocthEq0PefjWi2urnID+JhMZwaMD+cPMWXNpxKx556E1ICOABpqXX2VqwesWEWNQR4fJrZqbmkbI0gujCOO5W90sfoOQ0exFipudKJuyeb0N9XJXqCJjyzL+G503yqBpA6tnn8enPlgKGqELkV8YspQZVZ0F5nxJ3FxSL/prnDL+9MDuriXolfTkxhzhhfUTFrHZZEhxlpS92e1r1QCoNKXj4AJAM3PGLR0fxKKNQCVqxAENyPw4MvyIRnwFaxghhDHFIL75uBLmumudZdaLaz+DNejDsIZJZKlRgZzhdt/oJ4q8Tv4SLStLel/WQn2udoFcGHkljL0lxKAVGMtE7XOxd/S+TjuiGmKrXhY4DUGEAessayucxtJtgX4iZK1I79CIl8Kke82J4T9frDj6TNeaL/jGOUKoXRM1laqDiBYDP5EAdgjWPg57T8kNPdqZdoi2xRVVvKL3yXOFbUTF/hBf8UVl01pSxCpGD/Rbhemt3GJqQQR9GSejqxyvd60zA32WXFClejRVgyqm34+AHT2q+LVGLHYqQzjNJ3Cm/RerdvxAwBk=
{{- end }}
{{- if not (lookup "v1" "Secret" "platform-develop" "doppler") }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: doppler
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    doppler_token: AgBMyMt2GnMmBTx1zig+9TaWhbsBGNThZnJyNPS4hKn+kEdoYPtTZ1aQbGyN6LCyu7fiX9oJ6Bc00semYZ9Tf28x1J4KeZ+GAD75bsI4pab1t6aYpkPhkwZ+Xl3bzruqfEbOOU5BoqhOP4HLClpqSXmx+sMFkgAu7Gy5Xp1bF5frypKO+YLAeipyS6MyuoPgpviuihzIIQQHDZi83x+w5FMjWDe4wnVAzGWvwRVwiqlrLE0m2Sf7hCQPe2G7xsNQMEmc8+anJ6dLbaU0/G8ccLcH/tC3o7rxwf7tmfdgTHcOARlWEQ8hNdD3iNXeoMUGRMqgubcZJvxieHsGvlrNvFr9RO+jPTG6WW4ipKsIpWp4AV7oTrI7Dt//OCtoStPv10hklavNEO0MA5TpeFsbH7WoeJASjLpNYOv1lXz2YOK5aJvRZf11cmy64Gh7vSKgOJQq9D6CIF0KkqCEu5X/gtKhRz/B0H+JJv+Fa1ms1WN+gQgwb9gNcqwMTgV/dbpH8QRyLYkqsSRtrN43Ll++kM8m72CaLPlkN6uQGLG6/2WwVkZMUiB4LqisbtnOn/yJ521LFc7rZn2IXYgz6uHJdu9oPNg/hkh0yeOZ6nTgTk2z3mZI5fNic4L6mUv1nNWfLuneDC8oLo5iTnf4pxabzFRinxbQH8cQ9DG2++UxBnSmaewKyiFhrS4BYacgFZAvj3eY90TSiwrmAgJrSBXnP4Eidf349bg5EvM+Vaw4WkX6LCUj55EMDrpFdX2GIk9K86di7UGOgbo=
{{- end }}