services:
  # Controller network
  premiscale-single-host:
    container_name: premiscale-single-host
    platform: linux/amd64
    profiles:
      - single_host
    build:
      context: .
      dockerfile: ./Dockerfile
      target: develop
      pull: true
    environment:
      - PREMISCALE_TOKEN=123
      - PREMISCALE_CONFIG_PATH=/opt/premiscale/config.yaml
      - PREMISCALE_LOG_LEVEL=debug
      - PREMISCALE_PLATFORM=platform:443
      - PREMISCALE_CACERT=/opt/premiscale/cert.pem
      - INFLUXDB_HOST=influxdb:8086
      - INFLUXDB_USERNAME=premiscale
      - INFLUXDB_PASSWORD=premiscale
      - MYSQL_HOST=mysql-agent-state:3306
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-agent-state:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      echoes:
        condition: service_healthy
      registration:
        condition: service_healthy
      platform:
        condition: service_healthy
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem
      # Mount a different config from the default into the running container for testing.
      - ./src/tests/data/config/v1alpha1_base+qemu_single_host_no_asg.yaml:/opt/premiscale/config.yaml
    healthcheck:
      test: curl http://localhost:8085/healthcheck
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 8085:8085
  premiscale:
    container_name: premiscale
    platform: linux/amd64
    profiles:
      - zero
    build:
      context: .
      dockerfile: ./Dockerfile
      target: develop
      pull: true
    environment:
      - PREMISCALE_TOKEN=123
      - PREMISCALE_CONFIG_PATH=/opt/premiscale/config.yaml
      - PREMISCALE_LOG_LEVEL=debug
      - PREMISCALE_PLATFORM=platform:443
      - PREMISCALE_CACERT=/opt/premiscale/cert.pem
      - INFLUXDB_HOST=influxdb:8086
      - INFLUXDB_USERNAME=premiscale
      - INFLUXDB_PASSWORD=premiscale
      - MYSQL_HOST=mysql-agent-state:3306
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-agent-state:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      echoes:
        condition: service_healthy
      registration:
        condition: service_healthy
      platform:
        condition: service_healthy
    volumes:
      - ./certs/cert.pem:/opt/premiscale/cert.pem
    healthcheck:
      test: curl http://localhost:8085/healthcheck
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 8085:8085
  mysql-agent-state:
    container_name: mysql-agent
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=premiscale
      - MYSQL_DATABASE=premiscale
      - MYSQL_USER=premiscale
      - MYSQL_PASSWORD=premiscale
    ports:
      - 3306:3306
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 3
  influxdb:
    container_name: influxdb-agent
    image: influxdb:2.7.6
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=premiscale
      - DOCKER_INFLUXDB_INIT_PASSWORD=premiscale
      - DOCKER_INFLUXDB_INIT_ORG=premiscale
      - DOCKER_INFLUXDB_INIT_BUCKET=premiscale-local
    ports:
      - 8086:8086
    networks:
      - controller
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: influx ping || exit 1
      interval: 3s
      retries: 5
      start_period: 5s
      timeout: 5s

  # Platform network
  platform:
    container_name: nginx
    image: nginx:stable
    ports:
      - 443:443
    volumes:
      - ./compose.nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - platform
      - controller
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 300M
        reservations:
          cpus: '0.25'
          memory: 300M
    healthcheck:
      test: curl http://localhost/healthcheck
      interval: 3s
      retries: 3
      start_period: 10s
      timeout: 5s
    depends_on:
      registration:
        condition: service_healthy
      echoes:
        condition: service_healthy
  # test:
  #   image: ubuntu:22.04
  #   command: sleep inf
  #   networks:
  #     - platform
  #     - controller
  #   volumes:
  #     - ./certs:/certs
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 300M
  #       reservations:
  #         cpus: '0.25'
  #         memory: 300M
  echoes:
    container_name: premiscale-echoes
    build:
      context: ../echoes/
      dockerfile: Dockerfile.develop
    environment:
      - ECHOES_LISTEN_ADDRESS=0.0.0.0
      - ECHOES_LISTEN_HTTP_PORT=8081
      - ECHOES_LISTEN_WSS_PORT=8080
      - ECHOES_LOGLEVEL=debug
      - ECHOES_FLASK_WORKERS=1
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3037
      - MYSQL_DATABASE=premiscale
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=premiscale
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-platform:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:$$ECHOES_LISTEN_HTTP_PORT/agent/websocket/healthcheck
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3
  registration:
    container_name: premiscale-registration
    build:
      context: ../registration/
      dockerfile: Dockerfile.develop
    environment:
      - REGISTRATION_LISTEN_ADDRESS=0.0.0.0
      - REGISTRATION_LISTEN_PORT=8080
      - REGISTRATION_WORKERS=0
      - REGISTRATION_LOGLEVEL=debug
      - MYSQL_USERNAME=premiscale
      - MYSQL_PASSWORD=premiscale
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3037
      - MYSQL_DATABASE=premiscale
      - REDIS_HOST=localhost
      - REDIS_PORT=6379
      - REDIS_PASSWORD=premiscale
    ports:
      - 8082:8080
    networks:
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '1.0'
          memory: 1G
    depends_on:
      mysql-platform:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: curl http://localhost:$$REGISTRATION_LISTEN_PORT/agent/registration/healthcheck
      start_period: 2s
      interval: 5s
      timeout: 5s
      retries: 3
  redis:
    container_name: redis
    image: redis:7.2.5
    environment:
      - REDIS_PASSWORD=premiscale
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass $$REDIS_PASSWORD
    volumes:
      - cache:/data
    healthcheck:
      test: redis-cli ping
      interval: 3s
      retries: 5
      start_period: 2s
      timeout: 3s
  mysql-platform:
    container_name: mysql-platform
    image: mysql:8.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=premiscale
      - MYSQL_DATABASE=premiscale
      - MYSQL_USER=premiscale
      - MYSQL_PASSWORD=premiscale
    ports:
      - 3307:3306
    networks:
      - platform
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 1G
    healthcheck:
      test: mysqladmin ping -h localhost
      start_period: 3s
      interval: 5s
      timeout: 5s
      retries: 3
networks:
  controller:
    driver: bridge
    internal: false
  platform:
    driver: bridge
    internal: false
volumes:
  cache:
    driver: local