[tool.poetry]
name = "premiscale"
version = "0.0.1"
description = "PremiScale autoscaler"
authors = ["Emma Doyle <emma@premiscale.com>"]
maintainers = ["Emma Doyle <emma@premiscale.com>"]
license = "Proprietary"
readme = "README.md"
packages = [
  { include = "premiscale" }
]
include = [
  "LICENSE"
]
keywords = [
    "autoscaling",
    "asg",
    "kvm",
    "libvirt"
]

[tool.poetry.dependencies]
python = "^3.10"
yamale = "^4.0.4"
Flask = "^2.2.2"
websockets = "^11.0"
influxdb = "^5.3.1"
python-daemon = "3.0.1"
libvirt-python = "^9.0.0"
mysqlclient = "2.1.1"

[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"
pylint = "^2.15.10"
pre-commit = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
premiscale = "premiscale.agent.cli:main"