[tool.poetry]
name = "premiscale"
version = "0.0.1"
description = "PremiScale autoscaler"
authors = ["Emma Doyle <emma@premiscale.com>"]
maintainers = ["Emma Doyle <emma@premiscale.com>"]
license = "Proprietary"
readme = "README.md"
packages = [
  { include = "src" }
]
include = [
  "LICENSE"
]
keywords = [
    "autoscaling",
    "asg",
    "kvm",
    "libvirt"
]

[tool.poetry.dependencies]
python = "^3.10"
yamale = "^4.0.4"
Flask = "^2.3.2"
gunicorn = "^20.1.0"
flask-cors = "^3.0.10"
websockets = "^11.0"
influxdb = "^5.3"
python-daemon = "^3.0"
libvirt-python = "^9.0"
setproctitle = "^1.3"
sqlmodel = "^0.0"

[tool.poetry.group.dev.dependencies]
twine = "^4.0.2"
pylint = "^2.15.10"
pre-commit = "^3.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
premiscale = "src.premiscale.agent.cli:main"

[tool.mypy]
python_version = "3.10"
strict_optional = true
ignore_missing_imports = true