[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[tool.poetry]
name = "autoscaler"
version = "0.0.1"
description = "Libvirt autoscaler"
authors = ["Emma Doyle"]
