[tool.poetry]
name = "premiscale"
version = "0.0.1"
description = "PremiScale autoscaler"
authors = ["Emma Doyle <emma@premiscale.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
libvirt-python = "^8.10.0"
yamale = "^4.0.4"
Flask = "^2.2.2"

[tool.poetry.group.dev.dependencies]
setupext-janitor = "^1.1.2"
twine = "^4.0.2"
check-manifest = "^0.49"
tomlq = "^0.1.0"
pylint = "^2.15.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
