[tool.poetry]
name = "autoscaler"
version = "0.1.0"
description = "autoscaler for on-premise clouds"
authors = ["Emma Doyle <emma@premiscale.com>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
libvirt-python = "^8.10.0"

[tool.poetry.group.dev.dependencies]
libvirt-python = "^8.10.0"
yamale = "^4.0.4"
setupext-janitor = "^1.1.2"
PyYAML = "^6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
