global:
  imageRegistry: docker.ops.premiscale.com
  imagePullSecrets:
    - nexus-docker-registry
  storageClass: longhorn

image:
  name: mysql
  tag: latest
  pullPolicy: Always

auth:
  existingSecret: mysql-passwords
  database: autoscaler
  username: autoscaler

# Eventually I'll need these
initdbScripts: {}

resources:
  requests:
    cpu: 0.5
    memory: 500Mi
  limits:
    cpu: 1.0
    memory: 1Gi

persistence:
  enabled: true
  storageClass: longhorn
  accessModes:
    - ReadWriteOnce
  size: 1Gi

env: []

service:
  enabled: true