version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.6.10
  general: bjd2385/general@0.7.5
  slack: circleci/slack@4.12.5


workflows:
  premiscale:
    jobs:
      - dynamic/continue:
          context: circleci

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale]
          context: nexus
          path: helm/premiscale
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: pypi premiscale upload [python]
          context: nexus
          repository: python
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-nexus:
          name: docker [docker/premiscale]
          image-name: premiscale
          context: nexus
          path: docker/premiscale
          nexus-domain: $DOCKER_DOMAIN
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=$CIRCLE_TAG
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python
          tag: 0.0.<< pipeline.number >>
          requires:
            - pypi premiscale upload [python]
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-upgrade:
          name: helm upgrade install [helm/premiscale] [tag]
          cluster: $CHELSEA_CLUSTER
          namespace: agent-tags
          repo: $HELM_REPOSITORY_URL
          version: $CIRCLE_TAG
          # additional-values: |
          requires:
            - docker [docker/premiscale]
            - helm build and push [helm/premiscale]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore:
                - master