version: 2.1


orbs:
  general: bjd2385/general@dev:87b5f95e6da8e4c0341ccb6df3253abeaa5917a7

workflows:
  schema:
    jobs:
      - general/python-yamale:
          name: yamale [<< matrix.path >>]
          matrix:
            parameters:
              path:
                - tests/schema
                - conf/default.yaml
            alias: yamale
          schema-path: conf/schema.yaml
