version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.8.1
  general: premiscale/general@1.2.0
  slack: circleci/slack@4.12.6


executors:
  python-3-10-libvirt:
      docker:
        - image: docker.ops.premiscale.com/executors/python-3-10:1.0.6
          auth:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD


workflows:
  premiscale:
    jobs:
      - dynamic/continue:
          base-revision: master
          context: circleci

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          name: 'hold: create tagged release artifacts'
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          requires:
            - 'hold: create tagged release artifacts'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: pypi premiscale upload [python]
          executor: python-3-10-libvirt
          resource-class: premiscale/small
          context: nexus
          repository: python
          requires:
            - 'hold: create tagged release artifacts'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-nexus:
          name: docker [docker/premiscale]
          image-name: premiscale
          context: nexus
          path: .
          nexus-domain: $DOCKER_DOMAIN
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=$CIRCLE_TAG
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python
          tag: 0.0.<< pipeline.number >>
          requires:
            - pypi premiscale upload [python]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale]
          context: nexus
          path: helm/premiscale
          requires:
            - docker [docker/premiscale]
          image-tag-path: .deployment.image.tag
          pre-command: |+
            helm repo add premiscale "$HELM_REPOSITORY_URL" --username "$HELM_USERNAME" --password "$HELM_PASSWORD"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - slack/on-hold:
          name: 'slack: notify release tagged deployment hold'
          context: slack
          requires:
            - helm build and push [helm/premiscale]
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          name: 'hold: release tagged deployment'
          requires:
            - 'slack: notify release tagged deployment hold'
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-upgrade:
          name: helm upgrade install [helm/premiscale]
          cluster: $CHELSEA_CLUSTER
          namespace: platform-tags
          repo: $HELM_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.imageRegistry="$DOCKER_DOMAIN"
            --set global.platform.hostname="$APP_DOMAIN"
            --set mysql.enabled=true
            --set mysql.deployment.image.tag="$CIRCLE_TAG"
            --set influxdb.enabled=true
            --set influxdb.influxdb.image.repository="$DOCKER_DOMAIN"/influxdb
            --set influxdb.influxdb.image.tag="$CIRCLE_TAG"
          requires:
            - 'hold: release tagged deployment'
          context:
            - kubeconfig
            - premiscale
            - nexus
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
