version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.4.0


executors:
  default:
    docker:
      - image: cimg/base:stable

  python3-10:
    docker:
      - image: cimg/python:3.10.6


commands: {}


jobs:
  release:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install gh CLI
          command: |+
            wget https://github.com/cli/cli/releases/download/v2.9.0/gh_2.9.0_linux_amd64.deb -O gh.deb
            sudo dpkg -i gh.deb
      - run:
          name: Generate release
          command: |+
            # Get latest tag.
            git fetch --all --tags
            export LATEST_TAG="$(git tag | sort -V | tail -1)"
            echo "$LATEST_TAG"
            # Generate release from tag.
            echo "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null || true
            gh release create "$LATEST_TAG" --generate-notes

  release-pypi:
    executor: python3-10
    resource_class: small
    steps:
      - checkout
      - run:
          name: Build package.
          command: python setup.py sdist bdist_wheel
      - run:
          name: Publish package to PyPI.
          command: |
            pip install twine
            twine upload dist/* -u $PYPI_USERNAME -p $API_TOKEN

  release-helm:
    executor: default
    resource_class: small
    parameters:
      chart-path:
        description: Path to Helm chart we wish to package.
        type: string
        default: helm/
      package-path:
        description: Path to upload charts in gh-pages branch.
        type: string
        default: autoscaler/charts/development
      chart-type:
        description: Enum of either development or production (determines whether or not to respect Chart.yaml .version-values).
        type: enum
        enum:
          - development
          - production
        default: development
      github-user:
        description: Username of the repository owner or collaborator.
        type: string
        default: $GITHUB_USERNAME
      github-token:
        description: GitHub token env var to reference.
        type: string
        default: $GITHUB_TOKEN
      chart-releaser-version:
        description: Helm project chart-releaser (cr) binary version to install.
        type: string
        default: '1.4.1'
    steps:
      - run:
          name: Install chart-releaser
          command: |
            wget https://github.com/helm/chart-releaser/releases/download/v<< parameters.chart-releaser-version >>/chart-releaser_<< parameters.chart-releaser-version >>_linux_amd64.tar.gz -O chart-releaser.tar.gz
            tar -zxvf chart-releaser.tar.gz
            install cr /usr/loca/bin/cr
            rm LICENSE README.md cr chart-releaser.tar.gz
      - when:
          condition:
            equal:
              - << parameters.chart-type >>
              - development
          steps:
            - run:
                name: Replace chart version
                command: |
                  sed -i "s@^version:.*@version: $CIRCLE_SHA1@" << parameters.chart-path >>/Chart.yaml
      - run:
          name: 'chart-releaser: package'
          command: cr package << parameters.chart-path >>
      - run:
          name: 'chart-releaser: upload'
          command: cr upload --package-path << parameters.package-path >> --owner << parameters.github-user >> --git-repo $CIRCLE_REPOSITORY_URL --token << parameters.github-token >>
      - run:
          name: 'chart-releaser: index'
          command: cr index --package-path << parameters.package-path >> --owner << parameters.github-user >> --git-repo $CIRCLE_REPOSITORY_URL --token << parameters.github-token >>


workflows:
  autoscaler:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          modules: |
            /scripts
            /src
            /tests
            /docker/autoscaler
            /docker/influxdb
            /docker/mysql
            /helm

      - release:
          name: Create GitHub release from tag
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - release-pypi:
          context: pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - release-helm:
          context: github
          chart-path: helm/autoscaler
          package-path: autoscaler/charts/production
          chart-type: production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
