version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.4.1
  general: bjd2385/general@0.5.3


workflows:
  autoscaler:
    jobs:
      - dynamic/continue:
          context: circleci
          modules: |
            /scripts
            /src
            /tests
            /docker/autoscaler
            /docker/influxdb
            /docker/mysql
            /helm
            /conf

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      # - general/pypi-release:
      #     context: pypi
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      # - general/helm-release-github-pages:
      #     name: 'helm: release production chart'
      #     context: github
      #     chart-path: helm/autoscaler
      #     publish-path: charts/production
      #     chart-type: production
      #     git-ssh-key-fingerprint: "bd:7c:f9:c7:c2:b2:14:82:81:f9:25:75:58:dd:83:4a"
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
