version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.8.1
  general: premiscale/general@1.0.10
  slack: circleci/slack@4.12.5


workflows:
  premiscale:
    jobs:
      - dynamic/continue:
          base-revision: master
          context: circleci

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context: github
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale]
          context: nexus
          path: helm/premiscale
          requires:
            - request-approval
          image-tag-path: .deployment.image.tag
          pre-command: |+
            helm repo add premiscale "$HELM_REPOSITORY_URL" --username "$HELM_USERNAME" --password "$HELM_PASSWORD"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: pypi premiscale upload [python]
          context: nexus
          repository: python
          requires:
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/docker-nexus:
          name: docker [premiscale] [tag]
          image-name: premiscale
          context: nexus
          path: .
          nexus-domain: $DOCKER_DOMAIN
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=$CIRCLE_TAG
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python
          tag: 0.0.<< pipeline.number >>
          requires:
            - pypi premiscale upload [python]
            - request-approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/helm-upgrade:
          name: helm upgrade install [helm/premiscale]
          cluster: $CHELSEA_CLUSTER
          namespace: platform-tags
          repo: $HELM_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: |
            --set global.platform.hostname=app.premiscale.com --set global.registry=docker.ops.premiscale.com
          requires:
            - request-approval
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/