version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.8.2
  general: premiscale/general@dev:47e12776bac86661cf834339b3f32cc4b3fe89ae
  slack: circleci/slack@4.13.3


workflows:
  premiscale:
    jobs:
      - dynamic/continue:
          base-revision: master
          context: circleci

      - slack/on-hold:
          context: slack
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - request-approval:
          name: 'hold: create tagged release artifacts'
          requires:
            - slack/on-hold
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/github-release:
          name: Create GitHub release from tag
          context:
            - github
            - circleci
          requires:
            - 'hold: create tagged release artifacts'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      - general/python-release-poetry:
          name: python package [pypi]
          context:
            - pypi
          repository: pypi
          requires:
            - 'hold: create tagged release artifacts'
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      # - general/docker-hub:
      #     name: docker [docker/premiscale]
      #     image-name: premiscale
      #     context: nexus
      #     path: .
      #     args: >-
      #       --build-arg=PYTHON_PACKAGE_VERSION=$CIRCLE_TAG
      #       --build-arg=PYTHON_USERNAME=$DOCKER_USERNAME
      #       --build-arg=PYTHON_PASSWORD=$DOCKER_PASSWORD
      #       --build-arg=PYTHON_REPOSITORY=python
      #       --target=production
      #     tag: 0.0.<< pipeline.number >>
      #     requires:
      #       - 'hold: create tagged release artifacts'
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      # - general/docker-nexus:
      #     name: docker [docker/premiscale]
      #     image-name: premiscale
      #     context: nexus
      #     path: .
      #     nexus-domain: $DOCKER_DOMAIN
      #     args: >-
      #       --build-arg=PYTHON_PACKAGE_VERSION=$CIRCLE_TAG
      #       --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
      #       --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
      #       --build-arg=PYTHON_REPOSITORY=python
      #     tag: 0.0.<< pipeline.number >>
      #     requires:
      #       - pypi premiscale upload [python]
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/

      # - general/helm-release-nexus:
      #     name: helm build and push [helm/premiscale]
      #     context: nexus
      #     path: helm/premiscale
      #     requires:
      #       - docker [docker/premiscale]
      #     image-tag-path: .deployment.image.tag
      #     pre-command: |+
      #       helm repo add premiscale "$HELM_REPOSITORY_URL" --username "$HELM_USERNAME" --password "$HELM_PASSWORD"
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v?[0-9]+\.[0-9]+\.[0-9]+$/
