version: 2.1


setup: true


orbs:
  dynamic: bjd2385/dynamic-continuation@3.4.0
  helm: circleci/helm@2.0.1


executors:
  default:
    docker:
      - image: cimg/base:stable

  python3-10:
    docker:
      - image: cimg/python:3.10.6


commands: {}


jobs:
  release:
    executor: default
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install gh CLI
          command: |+
            wget https://github.com/cli/cli/releases/download/v2.9.0/gh_2.9.0_linux_amd64.deb -O gh.deb
            sudo dpkg -i gh.deb
      - run:
          name: Generate release
          command: |+
            # Get latest tag.
            git fetch --all --tags
            export LATEST_TAG="$(git tag | sort -V | tail -1)"
            echo "$LATEST_TAG"
            # Generate release from tag.
            echo "$GITHUB_TOKEN" | gh auth login --with-token 2>/dev/null || true
            gh release create "$LATEST_TAG" --generate-notes

  release-pypi:
    executor: python3-10
    resource_class: small
    steps:
      - checkout
      - run:
          name: Build package.
          command: python setup.py sdist bdist_wheel
      - run:
          name: Publish package to PyPI.
          command: |
            pip install twine
            twine upload dist/* -u $PYPI_USERNAME -p $API_TOKEN

  release-helm:
    executor: default
    resource_class: small
    parameters:
      chart-path:
        description: Path to Helm chart we wish to package.
        type: string
        default: helm/
      chart-type:
        description: Enum of either development or production (determines whether or not to respect Chart.yaml .version-values).
        type: enum
        enum:
          - development
          - production
        default: development
      publish-path:
        description: Which directory in gh-pages to publish this Helm chart.
        type: string
        default: charts/development
      pages-branch:
        description: GitHub pages branch to publish this Helm chart to.
        type: string
        default: gh-pages
    steps:
      - add_ssh_keys:
          fingerprints:
            - "bd:7c:f9:c7:c2:b2:14:82:81:f9:25:75:58:dd:83:4a"
      - checkout
      - helm/install-helm-client
      - when:
          condition:
            equal:
              - << parameters.chart-type >>
              - development
          steps:
            - run:
                name: Replace chart version
                command: |
                  sed -i "s@^version:.*@version: 0.0.<< pipeline.number >>@" << parameters.chart-path >>/Chart.yaml
      - run:
          name: 'helm: package'
          command: helm package << parameters.chart-path >> --dependency-update
      - run:
          name: 'helm: upload'
          command: |
            git add *.tgz
            git stash push *.tgz
            git reset --hard
            git checkout << parameters.pages-branch >>
            git stash apply
            mv *.tgz << parameters.publish-path >>
      - run:
          name: 'helm: index'
          command: helm repo index --url https://helm.aperiodicity.com/<< parameters.publish-path >> << parameters.publish-path >> --merge << parameters.publish-path >>/index.yaml
      - run:
          name: 'Push changes: << parameters.pages-branch >>'
          command: |
            git config --global user.email "ejd2385@github.com"
            git config --global user.name "Emma Doyle"
            git reset
            git add << parameters.publish-path >>/*
            git commit -m "Upload Helm artifact"
            git push


workflows:
  autoscaler:
    jobs:
      - dynamic/continue:
          context: orb-publishing
          modules: |
            /scripts
            /src
            /tests
            /docker/autoscaler
            /docker/influxdb
            /docker/mysql
            /helm

      - release:
          name: Create GitHub release from tag
          context: github
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - release-pypi:
          context: pypi
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

      - release-helm:
          context: github
          chart-path: helm/autoscaler
          publish-path: charts/production
          chart-type: production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
