version: 2.1


orbs:
  general: bjd2385/general@dev:ecb6fd6a61aa1a10f9cb4168b97408380ca40898


workflows:
  docker-autoscaler:
    jobs:
      - general/docker-nexus:
          name: docker [autoscaler]
          image-name: autoscaler
          context: nexus
          path: docker/autoscaler
          commit-tag: true
