version: 2.1


orbs:
  general: bjd2385/general@0.5.3


workflows:
  docker-autoscaler:
    jobs:
      - general/nexus-docker:
          name: docker [autoscaler]
          context: nexus
          path: docker/autoscaler
