version: 2.1


orbs:
  general: bjd2385/general@dev:736abbe57f9c425b1e2779cc7f0608f8c6599085


workflows:
  docker-autoscaler:
    jobs:
      - general/docker-nexus:
          name: docker [autoscaler] [develop]
          image-name: autoscaler
          context: nexus
          path: docker/autoscaler
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              ignore:
                - master

      - general/docker-nexus:
          name: docker [autoscaler] [master]
          image-name: autoscaler
          context: nexus
          path: docker/autoscaler
          nexus-domain: $DOCKER_MASTER_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              only:
                - master
