version: 2.1


orbs:
  general: bjd2385/general@dev:e64cff81e91386511909a87c6f221ddb12adadac


workflows:
  docker-autoscaler:
    jobs:
      - general/docker-nexus:
          name: docker [autoscaler]
          image-name: autoscaler
          context: nexus
          path: docker/autoscaler
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              ignore:
                - master

      - general/docker-nexus:
          name: docker [autoscaler]
          image-name: autoscaler
          context: nexus
          path: docker/autoscaler
          nexus-domain: $DOCKER_MASTER_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              only:
                - master
