version: 2.1


orbs:
  general: bjd2385/general@dev:ecb6fd6a61aa1a10f9cb4168b97408380ca40898


workflows:
  docker-influxdb:
    jobs:
      - general/docker-nexus:
          name: docker [influxdb]
          image-name: influxdb
          context: nexus
          path: docker/influxdb
          commit-tag: true
