version: 2.1


orbs:
  general: bjd2385/general@0.5.3


workflows:
  docker-mysql:
    jobs:
      - general/nexus-docker:
          name: docker [mysql]
          image-name: mysql
          context: nexus
          path: docker/mysql
          commit-tag: true
