version: 2.1


orbs:
  general: bjd2385/general@dev:b66c69da19f434072cd33c0394cad2270f8e2b3f


workflows:
  docker-influxdb:
    jobs:
      - general/docker-nexus:
          name: docker [influxdb]
          image-name: influxdb
          context: nexus
          path: docker/influxdb
          commit-tag: true
