version: 2.1


orbs:
  general: bjd2385/general@dev:32c89f92e446e0e34f493c209bdcc16065fd5458


workflows:
  docker-influxdb:
    jobs:
      - general/docker-nexus:
          name: docker [influxdb] [develop]
          image-name: influxdb
          context: nexus
          path: docker/influxdb
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              ignore:
                - master

      - general/docker-nexus:
          name: docker [influxdb] [master]
          image-name: influxdb
          context: nexus
          path: docker/influxdb
          nexus-domain: $DOCKER_MASTER_DOMAIN
          tag: 0.0.<< pipeline.number >>
          filters:
            branches:
              only:
                - master
