version: 2.1


orbs:
  general: bjd2385/general@0.4.2


workflows:
  docker-autoscaler:
    jobs:
      - general/github-ghcr:
          name: "Docker: autoscaler"
          context:
            - github
          image-name: autoscaler
          args: ''
          commit-tag: false
          path: docker/autoscaler
