version: 2.1


orbs:
  general: bjd2385/general@dev:b66c69da19f434072cd33c0394cad2270f8e2b3f


workflows:
  docker-autoscaler:
    jobs:
      - general/docker-nexus:
          name: docker [autoscaler]
          image-name: autoscaler
          context: nexus
          path: docker/autoscaler
          commit-tag: true
