version: 2.1


orbs:
  helm: circleci/helm@2.0.1
  general: bjd2385/general@0.4.0


workflows:
  helm:
    jobs:
      - general/helm-lint:
          chart-path: helm/autoscaler

      - general/helm-release-github-pages:
          name: 'helm: release development chart'
          context: github
          chart-path: helm/autoscaler
          git-ssh-key-fingerprint: 'bd:7c:f9:c7:c2:b2:14:82:81:f9:25:75:58:dd:83:4a'
          development-package-id: << pipeline.number >>
          filters:
            branches:
              ignore:
                - master
          requires:
            - general/helm-lint
