version: 2.1


orbs:
  general: bjd2385/general@dev:b66c69da19f434072cd33c0394cad2270f8e2b3f


workflows:
  helm-mysql:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/mysql]
          chart-path: helm/mysql

      - general/helm-release-nexus:
          name: helm build and push [helm/mysql]
          context: nexus
          path: helm/mysql
          repo-name: premiscale
          version: 0.0.<< pipeline.number >>
          requires:
            - helm lint [helm/mysql]
