version: 2.1


orbs:
  general: bjd2385/general@dev:779b9a75c999b2b79c98eaa35975aa566c592bc7


workflows:
  helm-autoscaler:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/autoscaler]
          chart-path: helm/autoscaler

      - general/helm-release-nexus:
          name: helm build and push [helm/autoscaler] [develop]
          context: nexus
          path: helm/autoscaler
          repo-name: premiscale
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          requires:
            - helm lint [helm/autoscaler]
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/autoscaler] [master]
          context: nexus
          path: helm/autoscaler
          repo-name: premiscale
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          requires:
            - helm lint [helm/autoscaler]
          filters:
            branches:
              only:
                - master