version: 2.1


orbs:
  general: bjd2385/general@0.7.5


workflows:
  helm-premiscale:
    jobs:
      - general/helm-lint:
          name: helm lint [helm/premiscale]
          chart-path: helm/premiscale

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale] [develop]
          context: nexus
          path: helm/premiscale
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          requires:
            - helm lint [helm/premiscale]
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale] [master]
          context: nexus
          path: helm/premiscale
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          requires:
            - helm lint [helm/premiscale]
          filters:
            branches:
              only:
                - master