version: 2.1


orbs:
  general: bjd2385/general@0.5.3


workflows:
  helm-influxdb:
    jobs:
      - general/helm-lint:
          chart-path: helm/influxdb

      - general/nexus-helm:
          name: helm [helm/influxdb]
          context: nexus
          path: helm/influxdb
          repo-name: premiscale
          version: 0.0.$CIRCLE_WORKFLOW_ID
          requires:
            - general/helm-lint
