version: 2.1

orbs:
  shellcheck: circleci/shellcheck@3.1.2

workflows:
  scripts:
    jobs:
      - shellcheck/check:
          matrix:
            parameters:
              dir:
                - scripts/
                - docker/autoscaler/scripts/
            alias: shellcheck
          external_sources: true
