version: 2.1


orbs:
  general: premiscale/general@dev:f9a5fcc260ef16c98e1546cfe675fb01bded15f5


executors:
  premiscale-libvirt:
    docker:
      - image: docker.


workflows:
  src-premiscale-config-data:
    jobs:
      - general/python-yamale:
          name: v1alpha1 default config schema validation
          executor: premiscale-libvirt
          path: src/premiscale/config/data/default.yaml
          schema-path: src/premiscale/config/data/schema.v1alpha1.yaml