version: 2.1


orbs:
  general: premiscale/general@1.0.12


executors:
  premiscale-libvirt:
    docker:
      - image: docker.


workflows:
  src-premiscale-config-data:
    jobs:
      - general/python-yamale:
          executor: premiscale-libvirt
          path: src/premiscale/config/data/default.yaml
          schema-path: src/premiscale/config/data/schema.v1alpha1.yaml