version: 2.1


orbs:
  general: bjd2385/general@0.4.0


executors: {}


commands: {}


jobs: {}


workflows: {}
  # src:
  #   jobs:
  #     - general/pypi-pylint:
  #         filters:
  #           branches:
  #             ignore:
  #               - master

  #     - general/pypi-mypy:
  #         name: mypy [<< matrix.executor >>]
  #         matrix:
  #           parameters:
  #             executor: [python3-10, python3-9, python3-8]
  #           alias: mypy
  #         filters:
  #           branches:
  #             ignore:
  #               - master
