version: 2.1


orbs:
  general: premiscale/general@1.0.12


executors:
  python-3-10:
    docker:
      - image: cimg/python:3.10.9

  python-3-10-libvirt:
    docker:
      - image: docker.ops.premiscale.com/executors/python-3-10:1.0.5
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD


workflows:
  src:
    jobs:
      - general/python-pylint:
          name: pylint
          executor: python-3-10-libvirt
          resource-class: premiscale/on-premise
          context: nexus

      - general/helm-lint:
          name: helm lint [helm/premiscale]
          chart-path: helm/premiscale

      # develop

      - general/python-release-poetry:
          name: twine upload [python-develop]
          executor: python-3-10-libvirt
          resource-class: premiscale/on-premise
          context: nexus
          repository: python-develop
          version: 0.0.<< pipeline.number >>
          requires:
            - pylint
          filters:
            branches:
              ignore:
                - master

      - general/docker-nexus:
          name: docker [premiscale] [develop]
          image-name: premiscale
          context: nexus
          path: docker/premiscale/Dockerfile
          nexus-domain: $DOCKER_DEVELOP_DOMAIN
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=0.0.<< pipeline.number >>
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python-develop
          tag: 0.0.<< pipeline.number >>
          requires:
            - twine upload [python-develop]
          filters:
            branches:
              ignore:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale] [develop]
          context: nexus
          path: helm/premiscale
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          image-tag-path: .deployment.image.tag
          pre-command: |+
            helm repo add premiscale "$HELM_DEVELOP_REPOSITORY_URL" --username "$HELM_USERNAME" --password "$HELM_PASSWORD"
          requires:
            - helm lint [helm/premiscale]
          filters:
            branches:
              ignore:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/premiscale] [develop]
          cluster: $CHELSEA_CLUSTER
          namespace: agent-develop
          repo: $HELM_DEVELOP_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: >-
            --set global.imageRegistry=docker-develop.ops.premiscale.com
          requires:
            - helm build and push [helm/premiscale] [develop]
            - docker [premiscale] [develop]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore:
                - master

      # master

      - general/python-release-poetry:
          name: twine upload [python-master]
          executor: python-3-10-libvirt
          resource-class: premiscale/on-premise
          context: nexus
          repository: python-master
          version: 0.0.<< pipeline.number >>
          requires:
            - pylint
          filters:
            branches:
              only:
                - master

      - general/docker-nexus:
          name: docker [premiscale] [master]
          image-name: premiscale
          context: nexus
          path: docker/premiscale/Dockerfile
          nexus-domain: $DOCKER_MASTER_DOMAIN
          args: >-
            --build-arg=PYTHON_PACKAGE_VERSION=0.0.<< pipeline.number >>
            --build-arg=PYTHON_USERNAME=$NEXUS_USERNAME
            --build-arg=PYTHON_PASSWORD=$NEXUS_PASSWORD
            --build-arg=PYTHON_REPOSITORY=python-master
          tag: 0.0.<< pipeline.number >>
          requires:
            - twine upload [python-master]
          filters:
            branches:
              only:
                - master

      - general/helm-release-nexus:
          name: helm build and push [helm/premiscale] [master]
          context: nexus
          path: helm/premiscale
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          image-tag: 0.0.<< pipeline.number >>
          image-tag-path: .deployment.image.tag
          pre-command: |+
            helm repo add premiscale "$HELM_MASTER_REPOSITORY_URL" --username "$HELM_USERNAME" --password "$HELM_PASSWORD"
          requires:
            - helm lint [helm/premiscale]
          filters:
            branches:
              only:
                - master

      - general/helm-upgrade:
          name: helm upgrade install [helm/premiscale] [master]
          cluster: $CHELSEA_CLUSTER
          namespace: agent-master
          repo: $HELM_MASTER_REPOSITORY_URL
          version: 0.0.<< pipeline.number >>
          additional-values: >-
            --set global.imageRegistry=docker-master.ops.premiscale.com
          requires:
            - helm build and push [helm/premiscale] [master]
            - docker [premiscale] [master]
          context:
            - kubeconfig
            - nexus
          filters:
            branches:
              ignore:
                - master