version: 2.1


orbs:
  general: bjd2385/general@dev:041d454e74fa99ea7e65bd77e527a081afe171c1


workflows:
  src:
    jobs:
      # develop

      - general/python-pylint:
          name: pylint [python-develop]
          filters:
            branches:
              ignore:
                - master

      - general/python-release-twine:
          name: twine upload [python-develop]
          context: nexus
          repository: python-develop
          requires:
            - pylint [python-develop]
          filters:
            branches:
              ignore:
                - master

      # master

      - general/python-pylint:
          name: pylint [python-master]
          filters:
            branches:
              only:
                - master

      - general/python-release-twine:
          name: twine upload [python-master]
          context: nexus
          repository: python-master
          requires:
            - pylint [python-master]
          filters:
            branches:
              only:
                - master