version: 2.1


orbs:
  general: premiscale/general@dev:43f32b5521ef87bfbc3563326981bfa93c307f90


executors:
  premiscale-libvirt:
    docker:
      - image: docker.


workflows:
  src-premiscale-config-data:
    jobs:
      - general/python-yamale:
          name: v1alpha1 default config schema validation
          executor: premiscale-libvirt
          path: src/premiscale/config/data/default.yaml
          schema-path: src/premiscale/config/data/schema.v1alpha1.yaml