version: 2.1


orbs:
  general: bjd2385/general@0.6.0


executors:
  python-3-10:
    docker:
      - image: cimg/python:3.10.6


commands:
  install-poetry:
    parameters:
      poetry-version:
        type: string
        description: Poetry version to install.
        default: 1.3.1
    steps:
      - run:
          command: |
            pip install --upgrade pip

            # Remove poetry from venv, install via pip.
            sudo rm /home/circleci/.local/bin/poetry
            pip install poetry==<< parameters.poetry-version >>
            sudo ln -s /home/circleci/.pyenv/shims/poetry /home/circleci/.local/bin/poetry
            poetry --version


jobs:
  pylint:
    executor: python-3-10
    resource_class: << parameters.resource-class >>
    parameters:
      resource-class:
        type: enum
        enum:
          - small
          - medium
          - large
          - xlarge
          - 2xlarge
        default: small
        description: Resource class to run as.
      modules_path:
        type: string
        description: Path to modules directory in package.
        default: src
      configuration_file:
        type: string
        description: Path to pylint configuration file
        default: .pylintrc
    steps:
      - checkout
      - install-poetry
      - run:
          name: Install dependencies with Poetry
          command: |
            # Install libvirt-python. Requires libvirt-dev package installed.
            if ! pkg-config --print-errors --atleast-version=0.9.11 libvirt 2>/dev/null; then
                sudo apt update && sudo apt install -y libvirt-dev
            fi

            poetry install -v --no-interaction --ansi --no-cache --sync || true

            pip install pylint
      - run:
          name: Pylint
          command: |
            pylint --rcfile=<< parameters.configuration_file >> << parameters.modules_path >>

  python-release-twine:
    executor: << parameters.executor >>
    resource_class: << parameters.resource-class >>
    environment:
      TWINE_NON_INTERACTIVE: true
    parameters:
      resource-class:
        type: enum
        enum:
          - small
          - medium
          - large
          - xlarge
          - 2xlarge
        default: small
        description: Resource class to run as.
      executor:
        type: executor
        default: python-3-10
        description: Executor to use
      user:
        description: PyPi username.
        type: string
        default: $TWINE_USERNAME
      password:
        description: PyPi API token.
        type: string
        default: $TWINE_PASSWORD
      repository:
        description: Repository name to upload to. Must have a URL set in .pypirc.
        type: string
        default: python
      config:
        description: Location of the .pypirc-file to use.
        type: string
        default: .pypirc
    steps:
      - checkout
      - install-poetry
      - run:
          name: Build package.
          command: |
            poetry build
      - run:
          name: Publish package to PyPI.
          command: |
            pip install twine
            twine upload dist/* -u << parameters.user >> -p << parameters.password >> --repository << parameters.repository >> --non-interactive --config-file << parameters.config >>


workflows:
  src:
    jobs:
      # develop

      - pylint:
          name: pylint [python-develop]
          filters:
            branches:
              ignore:
                - master

      - python-release-twine:
          name: twine upload [python-develop]
          context: nexus
          repository: python-develop
          # requires:
          #   - pylint [python-develop]
          filters:
            branches:
              ignore:
                - master

      # # master

      # - general/python-pylint:
      #     name: pylint [python-master]
      #     filters:
      #       branches:
      #         only:
      #           - master

      # - general/python-release-twine:
      #     name: twine upload [python-master]
      #     context: nexus
      #     repository: python-master
      #     requires:
      #       - pylint [python-master]
      #     filters:
      #       branches:
      #         only:
      #           - master