version: 2.1


# orbs:
#   general: bjd2385/general@0.6.0


executors:
  python-3-10:
    docker:
      - image: cimg/python:3.10.6


commands:
  install-poetry:
    description: Install poetry
    parameters:
      poetry-version:
        type: string
        description: Poetry version to install.
        default: 1.3.1
    steps:
      - run:
          name: Install poetry
          command: |
            pip install --upgrade pip

            # Remove poetry from venv, install via pip.
            sudo rm /home/circleci/.local/bin/poetry
            pip install poetry==<< parameters.poetry-version >>
            sudo ln -s /home/circleci/.pyenv/shims/poetry /home/circleci/.local/bin/poetry
            poetry --version


jobs:
  pylint:
    description: PyLint
    executor: python-3-10
    resource_class: << parameters.resource-class >>
    parameters:
      resource-class:
        type: enum
        enum:
          - small
          - medium
          - large
          - xlarge
          - 2xlarge
        default: small
        description: Resource class to run as.
      modules_path:
        type: string
        description: Path to modules directory in package.
        default: src
      configuration_file:
        type: string
        description: Path to pylint configuration file
        default: .pylintrc
    steps:
      - checkout
      - install-poetry
      - run:
          name: Install dependencies with Poetry
          command: |
            # Install libvirt-python. Requires libvirt-dev package installed.
            if ! pkg-config --print-errors --atleast-version=0.9.11 libvirt 2>/dev/null; then
                sudo apt update && sudo apt install -y libvirt-dev
            fi

            poetry install -v --no-interaction --ansi --no-cache --sync || true

            pip install pylint
      - run:
          name: Pylint
          command: |
            pylint --rcfile=<< parameters.configuration_file >> << parameters.modules_path >>

  release-twine:
    description: twine upload
    executor: << parameters.executor >>
    resource_class: << parameters.resource-class >>
    environment:
      TWINE_NON_INTERACTIVE: true
    parameters:
      resource-class:
        type: enum
        enum:
          - small
          - medium
          - large
          - xlarge
          - 2xlarge
        default: small
        description: Resource class to run as.
      executor:
        type: executor
        default: python-3-10
        description: Executor to use
      user:
        description: PyPi username.
        type: string
        default: $TWINE_USERNAME
      password:
        description: PyPi API token.
        type: string
        default: $TWINE_PASSWORD
      repository:
        description: Repository name to upload to. Must have a URL set in .pypirc.
        type: string
        default: python
      config:
        description: Location of the .pypirc-file to use.
        type: string
        default: .pypirc
      version:
        description: Override the version of the uploaded artifact in pyproject.toml. Mainly for development pipelines.
        type: integer
        default: -1
    steps:
      - checkout
      - install-poetry
      - unless:
          condition:
            equal: [<< parameters.version >>, -1]
          steps:
            - run:
                name: Update package version
                command: |
                  _VERSION="$(grep -oiP "(?<=version = \").*(?=\")" pyproject.toml)"

                  if [[ "$_VERSION" =~ ^[0-9]+.[0-9]+.[0-9]+$ ]]; then
                      sed "s@version = \"${_VERSION}\"@version = \"${_VERSION}a<< parameters.version >>\"@" pyproject.toml > pyproject.toml.tmp
                  elif [[ "$_VERSION" =~ ^[0-9]+.[0-9]+.[0-9]+a[0-9]+$ ]]; then
                      _VERSION_A="${_VERSION%%a*}"
                      sed "s@version = \"${_VERSION}\"@version = \"${_VERSION_A}a<< parameters.version >>\"@" pyproject.toml > pyproject.toml.tmp
                  fi

                  mv pyproject.toml.tmp pyproject.toml
      - run:
          name: Build package.
          command: |
            poetry build
      - run:
          name: Publish package to PyPI.
          command: |
            pip install twine
            twine upload dist/* -u << parameters.user >> -p << parameters.password >> --repository << parameters.repository >> --non-interactive --config-file << parameters.config >>


workflows:
  src:
    jobs:
      # develop

      - pylint:
          name: pylint [python-develop]
          resource-class: medium
          filters:
            branches:
              ignore:
                - master

      - release-twine:
          name: twine upload [python-develop]
          context: nexus
          repository: python-develop
          version: << pipeline.number >>
          # requires:
          #   - pylint [python-develop]
          filters:
            branches:
              ignore:
                - master

      # master

      - pylint:
          name: pylint [python-master]
          resource-class: medium
          filters:
            branches:
              only:
                - master

      - release-twine:
          name: twine upload [python-master]
          context: nexus
          repository: python-master
          version: << pipeline.number >>
          requires:
            - pylint [python-master]
          filters:
            branches:
              only:
                - master