apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml $.Values.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  serviceName: {{ .Chart.Name }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 12 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range $.Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Values.image.name }}
          image: {{ .Values.global.imageRegistry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml $.Values.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -ec
                # No spaces between -u and -p and their arguments.
                - |
                  mysqladmin status -uroot -p"${MYSQL_ROOT_PASSWORD}"
          {{- end }}
          {{- if .Values.env }}
          env:
            {{- toYaml $.Values.env | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: {{ .Chart.Name }}
              mountPath: {{ .Values.persistence.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Chart.Name }}
      spec:
        storageClassName: {{ .Values.global.storageClass }}
        accessModes:
          {{- range $.Values.persistence.accessModes }}
          - {{ . }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}