# https://github.com/23andMe/Yamale
version: enum('v1')
scaling:
  databases: map(include('databases'), min=2, max=2)
  hostGroups: list(include('hostGroups'), min=1)
  autoscalingGroups: list(include('autoscalingGroups'), min=1)
---
databases:
  state: include('state')
  metrics: include('metrics')
---
state:
  type: mysql
  connection: include('connection')
---
metrics:
  type: influxdb
  connection: include('connection')
  interval: int(min=0)
  evaluate: int(min=0)
  trailing: int(min=0)
---
connection:
  url: str()
  port: integer(min=1, max=65535)
  credentials:
    env:
      username: USERNAME
      password: PASSWORD
---
hostGroups: map(include('hostGroup'), key=str(equals='hostGroup'), min=1)
---
hostGroup: list(map())
---
autoscalingGroups:
---
autoscalingGroup:
