{{- with .Values.controller.registration }}
  {{- if .createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.global.namespace | default $.Release.Namespace }}
  {{- with .labels }}
  labels:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- range $k, $v := . }}
    {{ $k }}: {{ tpl $v $ }}
    {{- end }}
  {{- end }}
immutable: {{ .immutable }}
type: Opaque
data:
  {{ .key }}: {{ .value }}
  {{- end }}
{{- end }}