{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default .Chart.Name }}
  namespace: {{ .Values.global.namespace | default .Release.Namespace }}
  {{- with .Values.service.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.externalIPs }}
  externalIPs:
    {{- toYaml . }}
  {{- end }}
  ports:
    {{- range $k, $values := .Values.service.ports }}
    - name: {{ $k }}
      port: {{ $values.port }}
      targetPort: {{ $values.targetPort }}
      protocol: {{ $values.protocol }}
      {{- with $values.nodePort }}
      nodePort: {{ $values.nodePort }}
      {{- end }}
    {{- end }}
  selector: {{ include "premiscale.selectorLabels" . | nindent 4 }}
  {{- with .Values.service.healthCheckNodePort }}
  healthCheckNodePort: {{ . }}
  {{- end }}
  {{- with .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy | default "Cluster" }}
  {{- end }}
  {{- with .Values.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity | default "None" }}
  {{- end }}
  {{- if (((.Values.service.sessionAffinityConfig).clientIP).timeoutSeconds) }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityConfig.clientIP.timeoutSeconds }}
  {{- end }}
{{- end }}