version: enum('v1')
scaling:
  databases:
    state:
      type: mysql
      connection:
        url: str()
        port: integer(min=1, max=65535)
        credentials:
          env:
            username: str()
            password: str()
    metrics:
      type: influxdb
      connection:
        url: str()
        port: integer(min=1, max=65535)
        credentials:
          env:
            username: str()
            password: str()
      interval: 30s
      evaluate: 1m
      trailing: 2m
  hostGroups:
