apiVersion: v2
name: premiscale
description: Helm chart for deploying PremiScale, Inc. autoscaler
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: mysql
    repository: "@premiscale-master"
    alias: mysql
    version: 0.0.x
    condition: mysql.enabled
  - name: influxdb
    repository: "@premiscale-master"
    alias: influxdb
    version: 0.0.x
    condition: influxdb.enabled
  # - name: autoscaler/cluster-autoscaler
  #   repository: https://kubernetes.github.io/autoscaler
  #   alias: kubernetes-autoscaler
  #   version:
  #   condition: kubernetesAutoscaler.enabled