global:
  imageRegistry: docker.ops.premiscale.com
  imagePullSecrets:
    - nexus-docker-registry
  storageClass: longhorn

service:
  enabled: true
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

deployment:
  podSecurityContext: {}
  containerSecurityContext: {}

  image:
    name: premiscale
    tag: 0.0.315
    pullPolicy: Always

  resources:
    requests:
      cpu: 0.1
      memory: 300Mi
    limits:
      cpu: 4.0
      memory: 2Gi

  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.ops.premiscale.com/premiscale
    # argocd-image-updater.argoproj.io/write-back-method: git
    # argocd-image-updater.argoproj.io/git-branch: master

  api:
    enabled: false
    port: 8080

  env:
    - name: PREMISCALE_DEBUG
      value: 'false'
    - name: PREMISCALE_TOKEN
      value: ''

configMap:
  enabled: false
  config: |+
    Your PremiScale config file.
  mountPath: /opt/premiscale

# Enable / disable databases.
influxdb:
  enabled: false

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 1.0
      memory: 1Gi
mysql:
  enabled: false

  resources:
    requests:
      cpu: 0.25
      memory: 500Mi
    limits:
      cpu: 1.0
      memory: 1Gi

# Deploy the kubernetes autoscaler for PremiScale to connect to.
# Images are overridden to point at those that have been rebuilt to have a
# premiscale interface.
kubernetes-autoscaler:
  enabled: false

  image:
    repository: docker.ops.premiscale.com/cluster-autoscaler
    tag: v1.28.2
    pullPolicy: IfNotPresent

  resources:
    limits:
      cpu: 100m
      memory: 300Mi
    requests:
      cpu: 100m
      memory: 300Mi

  revisionHistoryLimit: 1

  # Pod securityContext
  securityContext: {}