global:
  imageRegistry: docker-develop.ops.premiscale.com
  imagePullSecrets:
    - nexus-docker-registry
  storageClass: longhorn

image:
  name: premiscale
  tag: 0.0.315
  pullPolicy: Always

annotations:
  argocd-image-updater.argoproj.io/image-list: docker-develop.ops.premiscale.com/premiscale